### ISSUE TITLE
Error while running run_multiple_species.sh

### ISSUE THREAD

**Issue by senramvx** [ridgelab/JustOrthologs#11]
Hi,
My name is Marcus, post-doc within Federal University of Itajubá-Brazil, and I'm have the following error while using run_multiple_species.sh:

marcus-senra@ubuntu:/media/marcus-senra/LabWork/Bioinformatics/JustOrthologs$ bash run_multiple_species.sh -i smallTest/wrapperTest/ -o outputDir/ -e output_ortholog_groups -f .fasta.gz -g .gff3
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_2337807'
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_8395652'
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_8121494'
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_6042419'
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_8956050'
Traceback (most recent call last):
  File "wrapper.py", line 240, in <module>
    os.remove(extract1)
OSError: [Errno 2] No such file or directory: '.extract_1_5979866'

I'm running it in a Ubuntu Ubuntu 20.04.2 LTS gnome 3.36.8
All required python libraries are install and python justOrthologs.py -q smallTest/orthologTest/bonobo.fa -s smallTest/orthologTest/human.fa -o output -c -t 6
Is working fine.

I was wondering you may have any thoughts that could help me identify the problem.

Thanks in advance.

**Comment by ridgelab** [comment]
Hello!

I am unable to replicate the error on my end when I ran the same command. `run_multiple_species.sh` simply iterates through every species in the directory and calls `wrapper.sh`, which reads the gff3 file/fasta file, sorts the CDS regions by the number of splice sites, and calls JustOrthologs. Does the wrapper.sh script work for you? Since JustOrthologs works for you, then perhaps it's an issue with python2 vs python3 being called by the wrapper. The wrapper calls python ${command}, so if you open both the wrapper and the run_multiple_species files and replace "python" with "python2," maybe that'll work. The README for the wrapper says which programs are run. You can try each of those steps individually to see what's causing the issue as well. My guess is that it's one of the first steps (like the gff3 parsing), but I'm not sure. Hope that helps.

**Comment by jhoangResearch** [comment]
Hi,
I'm Johnson Hoang, research tech at Harvey Mudd, and I seem to have a similar issue as sneramvx was having when trying to run the example bash script in the directory. I've check all the files and have checked that every python has a 2 appended to it. It appears to me the temp1, temp2, etc. in wrapper.py get's are placed in the highest directory level (the JustOrthologs-master in my case), and are have a .sort instead of .extract? 
![image](https://user-images.githubusercontent.com/51241810/159360499-33fa8a40-80b3-40b8-bf61-ef4bae978e92.png)
Any help trying to debug this would be appreciated.

Mahalo.
